language: node_js
node_js: stable
branches:
    only:
    - source
cache:
    apt: true
    yarn: true
    directories:
        - node_modules

before_install:
- git config --global user.name "burnettzhong"
- git config --global user.email "burnetzhong@yeah.net"

- curl -o- -L https://yarnpkg.com/install.sh | bash 
- export PATH=$HOME/.yarn/bin:$PATH 
- npm install -g hexo-cli

install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/burnettzhong/burnettzhong.github.io.git master
